#!/bin/bash

# Update package lists
sudo apt update && sudo apt upgrade

# Install Node.js and npm
curl -sL https://deb.nodesource.com/setup_18.x | sudo bash
sudo apt install -y nodejs

# Install clang
sudo apt install -y clang

# Install LLVM
sudo apt install -y llvm-14

# Install GCC
sudo apt install -y gcc

# Verify installations
node -v
npm -v
llvm-config --version
gcc --version
