#!/bin/bash

# Check for Homebrew, install if we don't have it
if test ! $(which brew); then
    echo "Installing homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update

# Install Node.js and npm
brew install node

# Install LLVM
brew install llvm

# Verify installations
node -v
npm -v
llvm-config --version
gcc --version
